// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC49WABYatbP8Zd1VxRellu9oW465_p0Pw',
    appId: '1:868764135818:web:54c64889e11b7d0b3f1873',
    messagingSenderId: '868764135818',
    projectId: 'realtimeposts',
    authDomain: 'realtimeposts.firebaseapp.com',
    storageBucket: 'realtimeposts.firebasestorage.app',
    measurementId: 'G-XP96KK6F86',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9mGoujFNEzZgwpxAIqSspLaKC7Wi-dIk',
    appId: '1:868764135818:android:a0474886d4a395ee3f1873',
    messagingSenderId: '868764135818',
    projectId: 'realtimeposts',
    storageBucket: 'realtimeposts.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4b4XF-iigMYz5y5QdpA2Lb7NtOSnEH5M',
    appId: '1:868764135818:ios:41d4170cd4d5b16e3f1873',
    messagingSenderId: '868764135818',
    projectId: 'realtimeposts',
    storageBucket: 'realtimeposts.firebasestorage.app',
    iosBundleId: 'com.example.posts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4b4XF-iigMYz5y5QdpA2Lb7NtOSnEH5M',
    appId: '1:868764135818:ios:41d4170cd4d5b16e3f1873',
    messagingSenderId: '868764135818',
    projectId: 'realtimeposts',
    storageBucket: 'realtimeposts.firebasestorage.app',
    iosBundleId: 'com.example.posts',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC49WABYatbP8Zd1VxRellu9oW465_p0Pw',
    appId: '1:868764135818:web:a87f271bd998844e3f1873',
    messagingSenderId: '868764135818',
    projectId: 'realtimeposts',
    authDomain: 'realtimeposts.firebaseapp.com',
    storageBucket: 'realtimeposts.firebasestorage.app',
    measurementId: 'G-HLL2V6PHJ3',
  );
}
